name: 'Free disk space'
description: 'Maximize the available disk space for OpenWrt build job'
branding:
  icon: 'crop'
  color: 'orange'
inputs:
  swap-size-gb:
    description: 'Swap space to create, in GB.'
    required: false
    default: '4'
  build-mount-path:
    description: 'Absolute path to the mount point where the build space will be available, defaults to github.workspace if unset.'
    required: false
runs:
  using: "composite"
  steps:
    - name: Show system
      shell: bash
      run: |
        echo -e "\e[1;32mMemory:\e[0m"
        free -h
        echo -e "\e[1;32mStorage:\e[0m"
        df -Th /
        echo

    - name: Free disk space
      shell: bash
      run: |
        BUILD_MOUNT_PATH="${{ inputs.build-mount-path }}"
        if [[ -z "$BUILD_MOUNT_PATH" ]]; then
          BUILD_MOUNT_PATH="${{ github.workspace }}"
        fi
        sudo mkdir -p "$BUILD_MOUNT_PATH"
        sudo find /opt -mindepth 1 -maxdepth 1 ! -name "*runner*" -exec rm -rf {} \;
        sudo rm -rf /usr/local/lib/android \
         /usr/lib/google-cloud-sdk \
         /usr/lib/jvm \
         /usr/lib/{clang-16,clang-17,llvm-16,llvm-17} \
         /usr/local/aws* \
         /usr/local/julia* \
         /usr/local/share/{chromium,powershell,vcpkg} \
         /usr/share/dotnet \
         /usr/share/swift
        sudo swapoff -a
        sudo rm -f /swapfile
        if [[ "${{ inputs.swap-size-gb }}" != 0 ]]; then
          echo "::group::  Create SWAP"
          sudo dd if=/dev/zero of="/mnt/swapfile" bs=1G count=${{ inputs.swap-size-gb }}
          sudo chmod 600 /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
          echo "::endgroup::"
        fi
        root_dev=$(df / | awk 'NR==2 {print $1}')
        mnt_dev=$(df /mnt | awk 'NR==2 {print $1}')
        if [[ "$root_dev" != "$mnt_dev" ]]; then
          echo "::group::  Create Volume Group"
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - ${{ inputs.swap-size-gb }})
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - ${{ inputs.root-reserve-gb }})
          sudo truncate -s "$mnt_size"G /mnt/mnt.img
          sudo truncate -s "$root_size"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/mapper/github-runner
          sudo mount /dev/mapper/github-runner "$BUILD_MOUNT_PATH"
          echo "::endgroup::"
        fi
        sudo chown -R runner:runner "$BUILD_MOUNT_PATH"
        sudo sysctl -w vm.drop_caches=3

    - name: Disk space report after modification
      shell: bash
      run: |
        echo -e "\n\e[1;32mMemory:\e[0m"
        sudo free -h
        echo -e "\e[1;32mAvailable Storage:\e[0m"
        sudo df -Th
