runs:
  using: "composite"
  steps:
    - name: Install LLVM
      shell: bash
      run: |
        export PATH="/opt/clang/bin:$PATH"
        echo "/opt/clang/bin" >> $GITHUB_PATH
        mkdir /opt/clang
        wget -q https://github.com/sbwml/redhat-llvm-project/releases/download/19.1.4/clang-19.1.4-x86_64-redhat-linux.tar.xz
        sudo tar --strip-components=1 -C /opt/clang -xf clang-19.1.4-x86_64-redhat-linux.tar.xz
        rm -rf clang-19.1.4-x86_64-redhat-linux.tar.xz
        clang --version
