runs:
  using: "composite"
  steps:
    - name: Install LLVM
      shell: bash
      run: |
        export PATH="/opt/clang/bin:$PATH"
        echo "/opt/clang/bin" >> $GITHUB_PATH
        sudo mkdir /opt/clang
        wget -q https://github.com/sbwml/openwrt-llvm-toolchain/releases/download/20.0.0/clang-20.0.0-x86_64-unknown-linux-gnu.tar.xz
        sudo tar --strip-components=1 -C /opt/clang -xf clang-*-x86_64-unknown-linux-gnu.tar.xz
        rm -rf clang-*-x86_64-unknown-linux-gnu.tar.xz
        clang --version
